# spring.application.name=jpa

server:
  port: 8181

spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: g7AzFEIVIjIyK3cDe7AQziOGx2wdOvZkeZQmnsJh1BRDSKpvYjvkvy8GypEoe34pGxYyGI7pSrIQHv0YGtt32Q==

# upload file path
upload:
  path: C:/todo_upload








